//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiciSendas.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeStrings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BiciSendas.Recursos.HomeStrings", typeof(HomeStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Baches.
        /// </summary>
        public static string Baches {
            get {
                return ResourceManager.GetString("Baches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Caídas.
        /// </summary>
        public static string Caidas {
            get {
                return ResourceManager.GetString("Caidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carril Bici.
        /// </summary>
        public static string CarrilBici {
            get {
                return ResourceManager.GetString("CarrilBici", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estación de tren.
        /// </summary>
        public static string EstacionTren {
            get {
                return ResourceManager.GetString("EstacionTren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incidencias.
        /// </summary>
        public static string Incidencias {
            get {
                return ResourceManager.GetString("Incidencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obras.
        /// </summary>
        public static string Obras {
            get {
                return ResourceManager.GetString("Obras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parking.
        /// </summary>
        public static string Parking {
            get {
                return ResourceManager.GetString("Parking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Talleres.
        /// </summary>
        public static string Talleres {
            get {
                return ResourceManager.GetString("Talleres", resourceCulture);
            }
        }
    }
}
